# Lab07: Discrete Fourier Transform

Реализовать алгоритм БПФ.


In [36]:
import numpy as np
PI2 = 2 * np.pi

Возьмём простой массив для примера:

In [37]:
ys = [0.9,0.7,-0.6,-0.6]
hs = np.fft.fft(ys)
hs

array([0.4+0.j , 1.5-1.3j, 0.2+0.j , 1.5+1.3j])

In [38]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

In [39]:
dft(ys)

array([0.4+0.0000000e+00j, 1.5-1.3000000e+00j, 0.2-1.2246468e-17j,
       1.5+1.3000000e+00j])

Разделение массива на элементы:

In [40]:
ys[::2] , ys[1::2]

([0.9, -0.6], [0.7, -0.6])

Не рекурсивный метод:

In [41]:
def my_fft(ys):
  He = dft(ys[::2])
  Ho = dft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

In [42]:
my_fft(ys)

array([0.4+0.0000000e+00j, 1.5-1.3000000e+00j, 0.2-1.2246468e-17j,
       1.5+1.3000000e+00j])

Заменим на рекурсивный вызов:

In [43]:
def my_fft(ys):
  if len(ys) == 1:
    return ys
  He = my_fft(ys[::2])
  Ho = my_fft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

In [44]:
my_fft(ys)

array([0.4+0.0000000e+00j, 1.5-1.3000000e+00j, 0.2-1.2246468e-17j,
       1.5+1.3000000e+00j])